#!/usr/bin/env bash
# Set up this checkout for work: the pinned Haxe 5 compiler (`.haxe`), the test libraries, the test config
# (`.haxe-tests.hxml`), Serena's Haxe language server (`.serena/`) and ast-grep with a Haxe grammar
# (`.ast-grep/`). Everything it writes is gitignored.
#
#   bash tools/setup.sh      # once per checkout/worktree, and again after adding or removing source files;
#                            # restart Serena afterwards
#
# The compiler is the build of GeTechG/haxe named by tools/haxe-build.pin: one line, `<build key> <sha256 of
# the archive>`. To change the compiler, change that file. Only a Linux x86_64 build is published.
# Downloads and builds are shared by every checkout, one directory per pin, under
# ${XDG_CACHE_HOME:-~/.cache}/haxe-toolchain; nothing there is ever removed automatically.
# Needs curl, sha256sum, tar, git, flock, node, npm and cc.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/haxe-toolchain"

read -r KEY SUM < "$ROOT/tools/haxe-build.pin"
[[ $KEY =~ ^[0-9a-f]{40}$ && $SUM =~ ^[0-9a-f]{64}$ ]] || { echo "setup: tools/haxe-build.pin is not '<build key> <sha256>'" >&2; exit 1; }
HAXE="$CACHE/haxe/$KEY"

# The published vshaxe only speaks `--wait stdio`, which Haxe 5 dropped; this commit talks to the compiler
# over a socket.
LS_COMMIT=e865ce6ffa9299960d558728948691b7a5e9d4a2
LS="$CACHE/language-server/$LS_COMMIT"

# Test libraries, pinned by commit: the released utest (1.13.2) does not compile on Haxe 5.
HXJSONAST="$CACHE/lib/hxjsonast/3131eb00097ab6c6be2d43094189d5c4254dcb8c" # 1.1.0
UTEST="$CACHE/lib/utest/a055e05e2e872ae12a32b53d0200612345059c38"
LIBS="-cp $HXJSONAST/src
-D hxjsonast=1.1.0
-cp $UTEST/src
-D utest=2.0.0-alpha"

# ast-grep (the npm package: node and npm are needed for the language server anyway) and the tree-sitter
# grammar that sgconfig.yml loads into it. The grammar repository commits its generated parser, so the C
# compiler is the whole build.
SG_VERSION=0.45.3
SG="$CACHE/ast-grep/$SG_VERSION"
GRAMMAR="$CACHE/tree-sitter-haxe/31ae7eb010e18975fd73cd65e14c71ef5054f9c7"

# provide <dir> <command...>: unless <dir> exists, run the command with a temporary sibling as its last
# argument and rename that into place, so <dir> only ever appears complete.
TMP=
trap 'rm -rf "$TMP"' EXIT
provide() {
  local dir=$1; shift
  [ -e "$dir" ] && return
  TMP="$(mktemp -d "$dir.tmp.XXXXXX")"
  "$@" "$TMP"
  chmod 755 "$TMP"
  mv -T "$TMP" "$dir" 2> /dev/null || [ -e "$dir" ] # another setup finished first: same pin, same content
}

fetch_haxe() {
  local url="https://github.com/GeTechG/haxe/releases/download/builds/haxe-linux64-$KEY.tar.gz"
  echo "setup: downloading $url"
  curl -fsSL --retry 3 -o "$1/haxe.tar.gz" "$url"
  echo "$SUM  $1/haxe.tar.gz" | sha256sum -c --quiet - || { echo "setup: the build does not match tools/haxe-build.pin" >&2; exit 1; }
  tar -xzf "$1/haxe.tar.gz" -C "$1"
  rm "$1/haxe.tar.gz"
  [ -x "$1/haxe" ] && [ -d "$1/std" ] || { echo "setup: the build holds no haxe + std/" >&2; exit 1; }
}

fetch_commit() { # <url> <commit> <dir>
  git init -q "$3"
  git -C "$3" fetch -q --depth 1 "$1" "$2"
  git -C "$3" checkout -q FETCH_HEAD
}

build_ls() {
  echo "setup: building haxe-language-server $LS_COMMIT (a few minutes, once)"
  fetch_commit https://github.com/vshaxe/haxe-language-server "$LS_COMMIT" "$1"
  (cd "$1" && npm ci --silent && npx lix run vshaxe-build -t language-server > /dev/null)
  [ -f "$1/bin/server.js" ] || { echo "setup: the language server build left no bin/server.js" >&2; exit 1; }
}

install_sg() {
  echo "setup: installing ast-grep $SG_VERSION"
  npm install --silent --no-save --no-package-lock --prefix "$1" "@ast-grep/cli@$SG_VERSION"
  [ "$("$1/node_modules/.bin/ast-grep" --version)" = "ast-grep $SG_VERSION" ] || { echo "setup: npm left no ast-grep $SG_VERSION" >&2; exit 1; }
}

build_grammar() { # <commit> <dir>
  fetch_commit https://github.com/GeTechG/tree-sitter-haxe "$1" "$2"
  cc -shared -fPIC -O2 -I "$2/src" "$2"/src/*.c -o "$2/haxe.so"
}

LOCAL="$ROOT/.serena/project.local.yml"
MARK="# GENERATED by tools/setup.sh"
# A comment-only file is the template Serena itself drops next to a project.yml it generates: nothing to lose.
if [ -f "$LOCAL" ] && grep -qv '^\s*\(#\|$\)' "$LOCAL" && ! grep -qF "$MARK" "$LOCAL"; then
  echo "setup: $LOCAL holds your own overrides; move them aside and re-run" >&2
  exit 1
fi

# One setup at a time per user: a second checkout waits here, then finds everything in place.
mkdir -p "$CACHE/haxe" "$CACHE/language-server" "$CACHE/lib/hxjsonast" "$CACHE/lib/utest" "$CACHE/ast-grep" "$CACHE/tree-sitter-haxe"
exec 9> "$CACHE/.lock"
flock 9
provide "$HAXE" fetch_haxe
provide "$HXJSONAST" fetch_commit https://github.com/nadako/hxjsonast "${HXJSONAST##*/}"
provide "$UTEST" fetch_commit https://github.com/haxe-utest/utest "${UTEST##*/}"
provide "$LS" build_ls
provide "$SG" install_sg
provide "$GRAMMAR" build_grammar "${GRAMMAR##*/}"
flock -u 9

ln -sfn "$HAXE" "$ROOT/.haxe"
mkdir -p "$ROOT/.ast-grep"
ln -sfn "$SG/node_modules/.bin/ast-grep" "$ROOT/.ast-grep/ast-grep"
ln -sfn "$GRAMMAR/haxe.so" "$ROOT/.ast-grep/haxe.so"

# The interpreter test build (tests/build/build_interp.hxml) with its `-lib`s spelled out, so it needs no haxelib.
COMMON="$ROOT/tests/build/build_common.hxml"
{
  echo "$MARK — do not edit."
  echo "$LIBS"
  echo "--macro utest.utils.Macro.importEnvSettings()"
  grep -v '^-lib ' "$COMMON"
  echo "--interp"
} > "$ROOT/.haxe-tests.hxml"

# The display config. The language server sends these arguments to the compiler over a socket, so: no `-lib`,
# no `--macro`, and every module named — with none named the compiler's cache build types nothing and a
# reference lookup silently returns only part of the references.
modules() { # <classpath> [<package>]
  (cd "$ROOT/$1/${2:-}" && find . -name '*.hx' ! -name import.hx) | sed -e "s|^\./|${2:+$2/}|" -e 's|\.hx$||' -e 's|/|.|g'
}
mkdir -p "$ROOT/.serena"
{
  echo "$MARK — do not edit."
  echo "# tests/ is typed here together with src/ (modules tests.*). References the compiler still does not"
  echo "# report — @:genericBuild types, enum constructors in case patterns, imports — are listed in AGENTS.md."
  echo "$LIBS"
  grep '^-cp ' "$COMMON"
  echo "-w -WIfDisplay"
  { modules src; modules patched_utest; modules . tests; } | sort -u
} > "$ROOT/.serena/lsp.hxml"

# Serena overwrites project.local.yml when it has to generate a missing project.yml.
[ -f "$ROOT/.serena/project.yml" ] || printf 'language_servers:\n- haxe\n' > "$ROOT/.serena/project.yml"
cat > "$LOCAL" << YAML
$MARK — do not edit.
language_servers:
- haxe
ls_specific_settings:
  haxe:
    buildFile: .serena/lsp.hxml
    ls_base_cmd: ["sh", "-c", 'PATH="\$PWD/.haxe:\$PATH" HAXE_STD_PATH="\$PWD/.haxe/std" exec node "$LS/bin/server.js"']
    ls_args: []
YAML

echo "setup: $("$ROOT/.haxe/haxe" --version) at .haxe, language server $LS_COMMIT, ast-grep $SG_VERSION at .ast-grep; restart Serena"
